In [1]:
import numpy as np
from keras.datasets import mnist
import keras
from keras import layers
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
training_set, test_set = mnist.load_data()
X_train, y_train = training_set
X_test, y_test = test_set
print(X_train.shape)

(60000, 28, 28)


In [3]:
X_train = np.expand_dims(X_train, -1)
X_test = np.expand_dims(X_test, -1)
print(X_train.shape)
X_train = X_train.astype(np.float) / 255.0  
X_test = X_test.astype(np.float) / 255.0

(60000, 28, 28, 1)


C:\Users\Tristan\AppData\Local\Temp\ipykernel_12584\3163765972.py:4: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_train = X_train.astype(np.float) / 255.0
C:\Users\Tristan\AppData\Local\Temp\ipykernel_12584\3163765972.py:5: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_test = X_test.astype(np.float) / 255.0


In [4]:
num_classes = 10
input_shape = (28, 28, 1)
batch_size = 128
epochs = 30

model = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            keras.layers.Flatten(),
            layers.Dense(num_classes, activation="softmax")
        ]
    )

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 10)                7850      
                                                                 
Total params: 7,850
Trainable params: 7,850
Non-trainable params: 0
_________________________________________________________________


In [5]:
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [6]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
375/375 [==============================] - 1s 1ms/step - loss: 0.7419 - accuracy: 0.8196 - val_loss: 0.4089 - val_accuracy: 0.8986
Epoch 2/30
375/375 [==============================] - 0s 765us/step - loss: 0.3890 - accuracy: 0.8966 - val_loss: 0.3352 - val_accuracy: 0.9112
Epoch 3/30
375/375 [==============================] - 0s 762us/step - loss: 0.3381 - accuracy: 0.9083 - val_loss: 0.3079 - val_accuracy: 0.9155
Epoch 4/30
375/375 [==============================] - 0s 784us/step - loss: 0.3147 - accuracy: 0.9133 - val_loss: 0.2947 - val_accuracy: 0.9193
Epoch 5/30
375/375 [==============================] - 0s 778us/step - loss: 0.3001 - accuracy: 0.9165 - val_loss: 0.2880 - val_accuracy: 0.9196
Epoch 6/30
375/375 [==============================] - 0s 778us/step - loss: 0.2905 - accuracy: 0.9192 - val_loss: 0.2786 - val_accuracy: 0.9222
Epoch 7/30
375/375 [==============================] - 0s 760us/step - loss: 0.2839 - accuracy: 0.9209 - val_loss: 0.2751 - val_accuracy: 0

In [7]:
y_probab = model.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

313/313 [==============================] - 0s 439us/step
              precision    recall  f1-score   support

           0       0.95      0.98      0.97       980
           1       0.97      0.98      0.98      1135
           2       0.94      0.90      0.92      1032
           3       0.90      0.92      0.91      1010
           4       0.94      0.93      0.94       982
           5       0.92      0.87      0.89       892
           6       0.93      0.96      0.95       958
           7       0.93      0.93      0.93      1028
           8       0.87      0.90      0.89       974
           9       0.91      0.91      0.91      1009

    accuracy                           0.93     10000
   macro avg       0.93      0.93      0.93     10000
weighted avg       0.93      0.93      0.93     10000

[[ 959    0    1    2    0    6    9    2    1    0]
 [   0 1112    3    2    0    1    4    2   11    0]
 [   6    9  925   17    6    3   14    9   40    3]
 [   3    0   17  927    

In [8]:
num_classes = 32
input_shape = (28, 28, 1)
batch_size = 128
epochs = 30

model = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            keras.layers.Flatten(),
            layers.Dense(64, activation="tanh"),
            layers.Dense(128, activation="tanh"),
            layers.Dense(num_classes, activation="softmax")
        ]
    )
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_1 (Flatten)         (None, 784)               0         
                                                                 
 dense_1 (Dense)             (None, 64)                50240     
                                                                 
 dense_2 (Dense)             (None, 128)               8320      
                                                                 
 dense_3 (Dense)             (None, 32)                4128      
                                                                 
Total params: 62,688
Trainable params: 62,688
Non-trainable params: 0
_________________________________________________________________


In [9]:
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
375/375 [==============================] - 1s 1ms/step - loss: 0.4702 - accuracy: 0.8776 - val_loss: 0.2247 - val_accuracy: 0.9351
Epoch 2/30
375/375 [==============================] - 0s 1ms/step - loss: 0.1980 - accuracy: 0.9411 - val_loss: 0.1676 - val_accuracy: 0.9519
Epoch 3/30
375/375 [==============================] - 0s 1ms/step - loss: 0.1431 - accuracy: 0.9575 - val_loss: 0.1356 - val_accuracy: 0.9617
Epoch 4/30
375/375 [==============================] - 0s 1ms/step - loss: 0.1100 - accuracy: 0.9676 - val_loss: 0.1277 - val_accuracy: 0.9631
Epoch 5/30
375/375 [==============================] - 0s 1ms/step - loss: 0.0892 - accuracy: 0.9734 - val_loss: 0.1122 - val_accuracy: 0.9664
Epoch 6/30
375/375 [==============================] - 0s 1ms/step - loss: 0.0727 - accuracy: 0.9783 - val_loss: 0.1071 - val_accuracy: 0.9693
Epoch 7/30
375/375 [==============================] - 0s 1ms/step - loss: 0.0612 - accuracy: 0.9821 - val_loss: 0.1067 - val_accuracy: 0.9677
Epoch 

In [10]:
y_probab = model.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

313/313 [==============================] - 0s 477us/step
              precision    recall  f1-score   support

           0       0.98      0.99      0.98       980
           1       0.98      0.99      0.99      1135
           2       0.98      0.96      0.97      1032
           3       0.97      0.96      0.97      1010
           4       0.97      0.97      0.97       982
           5       0.97      0.97      0.97       892
           6       0.97      0.97      0.97       958
           7       0.97      0.97      0.97      1028
           8       0.97      0.97      0.97       974
           9       0.97      0.97      0.97      1009

    accuracy                           0.97     10000
   macro avg       0.97      0.97      0.97     10000
weighted avg       0.97      0.97      0.97     10000

[[ 967    1    1    1    1    0    3    1    2    3]
 [   0 1128    2    1    0    0    1    1    2    0]
 [   9    4  992    2    1    1    5    8    9    1]
 [   0    1    7  974    

In [11]:
num_classes = 128
input_shape = (28, 28, 1)
batch_size = 128
epochs = 30

model = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            layers.Conv2D(32, kernel_size=(3, 3), activation="relu"),
            layers.MaxPooling2D(pool_size=(2, 2)),
            layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
            layers.MaxPooling2D(pool_size=(2, 2)),
            layers.Flatten(),
            layers.Dropout(0.5),
            layers.Dense(num_classes, activation="softmax"),
        ]
    )
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 13, 13, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 11, 11, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 5, 5, 64)         0         
 2D)                                                             
                                                                 
 flatten_2 (Flatten)         (None, 1600)              0         
                                                                 
 dropout (Dropout)           (None, 1600)             

In [12]:
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
375/375 [==============================] - 9s 22ms/step - loss: 0.5400 - accuracy: 0.8371 - val_loss: 0.1208 - val_accuracy: 0.9653
Epoch 2/30
375/375 [==============================] - 8s 22ms/step - loss: 0.1444 - accuracy: 0.9556 - val_loss: 0.0793 - val_accuracy: 0.9781
Epoch 3/30
375/375 [==============================] - 8s 22ms/step - loss: 0.0985 - accuracy: 0.9703 - val_loss: 0.0692 - val_accuracy: 0.9790
Epoch 4/30
375/375 [==============================] - 8s 22ms/step - loss: 0.0818 - accuracy: 0.9743 - val_loss: 0.0520 - val_accuracy: 0.9854
Epoch 5/30
375/375 [==============================] - 8s 22ms/step - loss: 0.0694 - accuracy: 0.9780 - val_loss: 0.0500 - val_accuracy: 0.9853
Epoch 6/30
375/375 [==============================] - 8s 22ms/step - loss: 0.0618 - accuracy: 0.9806 - val_loss: 0.0463 - val_accuracy: 0.9867
Epoch 7/30
375/375 [==============================] - 8s 22ms/step - loss: 0.0554 - accuracy: 0.9824 - val_loss: 0.0469 - val_accuracy: 0.9866

In [13]:
y_probab = model.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

313/313 [==============================] - 1s 2ms/step
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       980
           1       0.99      1.00      1.00      1135
           2       0.99      0.99      0.99      1032
           3       0.99      0.99      0.99      1010
           4       1.00      0.99      0.99       982
           5       0.99      0.99      0.99       892
           6       1.00      0.99      0.99       958
           7       0.99      0.99      0.99      1028
           8       0.99      0.99      0.99       974
           9       0.99      0.99      0.99      1009

    accuracy                           0.99     10000
   macro avg       0.99      0.99      0.99     10000
weighted avg       0.99      0.99      0.99     10000

[[ 978    0    0    0    0    0    0    1    1    0]
 [   0 1134    1    0    0    0    0    0    0    0]
 [   1    3 1022    0    0    0    1    5    0    0]
 [   0    0    2 1004    0 